### ISSUE TITLE
Configuration for rule "@typescript-eslint/no-misused-promises" is invalid

### ISSUE THREAD

**Issue by googol7** [molindo/eslint-config-molindo#103]
```
.eslintrc.js » eslint-config-molindo/typescript#overrides[0]:
	Configuration for rule "@typescript-eslint/no-misused-promises" is invalid:
	Value {"attributes":false} should be boolean.
```

See:
- https://github.com/molindo/eslint-config-molindo/issues/86

**Comment by googol7** [comment]
It was a local problem.

**Comment by googol7** [comment]
See https://github.com/molindo/eslint-config-molindo/blob/master/typescript.js#L50-L53

Both should work according to https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-misused-promises.mdx

```
'@typescript-eslint/no-misused-promises': [
  ERROR,
  {checksVoidReturn: {attributes: false}}
],
```

```
'@typescript-eslint/no-misused-promises': [
  ERROR,
  {checksVoidReturn: false}
],
```

**Comment by googol7** [comment]
It was a problem when
- Using `"react-scripts": "^4.0.3"` (in `package.json`)
- `DISABLE_ESLINT_PLUGIN=false` in `.env`
- Running `npm run build`

**Comment by amannn** [comment]
I couldn't reproduce this, seems like this was resolved.
