### ISSUE TITLE
Also allow tests in subdirectories

### ISSUE THREAD

**Issue by googol7** [molindo/eslint-config-molindo#16]
In a subdirectory 
src/utils/__tests__/subdir/something-test.js
I get this error:

`import sinon from „sinon"`

> 'sinon' should be listed in the project's dependencies, not devDependencies.

In the root level it works without problems:
src/utils/__tests__/semething-test.js
`import sinon from „sinon“`

This is because of:

```
   'import/no-extraneous-dependencies': [
     ERROR,
     {
       devDependencies: [
         'webpack.config.js',
         '**/__testUtils__/**/*.js',
         '**/__tests__/*-test.js'
       ]
     }
   ],
```

**Comment by amannn** [comment]
@googol7 Fixed and released in [3.0](https://github.com/molindo/eslint-config-molindo/releases/tag/3.0).
