### ISSUE TITLE
Remove `react/react-in-jsx-scope`

### ISSUE THREAD

**Issue by amannn** [molindo/eslint-config-molindo#55]
… since `import React from 'react';` is no longer necessary with [the new JSX transform](https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) (available both [in React 16](https://github.com/facebook/react/blob/master/CHANGELOG.md#16140-october-14-2020) as well as React 17).

**Comment by symn** [comment]
I am going to miss it though 😅

**Comment by amannn** [comment]
Haha, you can write it on a post-it and put it on your display if you like 😉
